#undef HAVE_AVIFILE
#undef HAVE_LAME
#undef HAVE_LAME_INC
#undef HAVE_OGG
#undef HAVE_VORBIS
#undef HAVE_DV
#undef HAVE_A52
#undef HAVE_LIBXV
#undef HAVE_GTK
#undef HAVE_SDL
#undef HAVE_MAGICK
#undef HAVE_X11
#undef HAVE_LIBMPEG3
#undef HAVE_QT
#undef HAVE_OPENQT
#undef HAVE_LIBPOSTPROC
#undef HAVE_MJPEG
#undef HAVE_V4L
#undef HAVE_LIBFAME
#undef HAVE_LIBXML2
#undef HAVE_LIBJPEG
#undef HAVE_LIBDVDREAD
#undef HAVE_LIBDVDREAD_INC

#undef HAVE_MMX
#undef HAVE_SSE
#undef HAVE_ASM_3DNOW
#undef HAVE_CMOV
#undef HAVE_ASM_NASM
#undef HAVE_ASM_MMX
#undef HAVE_PPC_ALTIVEC
#undef HAVE_X86CPU
#undef ARCH_X86
#undef ARCH_PPC

#undef WORDS_BIGENDIAN

#undef STATBUFFER
#undef NET_STREAM
#undef USE_LIBA52_DECODER

#undef AVIFILE_0_6
#undef LAME_3_89
#undef TRANSCODE_0_6
#undef LIBDV_095





