.TH avimerge 1 "25th June 2003" "avimerge(1)"
.SH NAME
avimerge \- merge several AVI-files into one
.SH SYNOPSIS
.na
.B avimerge
[
.B -o
.I name
.B -i
.IB file " ..."
.B -p
.IB file
.B -a
.I num
.B -b
.I num
.B -f
.I commentfile
]
.SH COPYRIGHT
\fBavimerge\fP is Copyright (C) by Thomas Östreich.
.SH DESCRIPTION
.B avimerge
merges several AVI-files into one.
.SH OPTIONS
.TP
\fB-o\fP \fIname\fP
Specify the name of the output file.
.TP
\fB-i\fP \fIfile\fP
Specify the name(s) of the input file(s) to merge into the output
file.
.TP
\fB-p\fP \fIfile\fP
Specify the name of the audio file to multiplex into the output file. The type
of file can be either another AVI file or an MP3 or AC3 file.
.TP
\fB-b\fP \fInum\fP
Specify if avisync should write an VBR mp3 header into the AVI file. Default is
1 because it does not hurt. \fInum\fP is either 1 or 0.
.TP
\fB-f\fP \fIcommentfile\fP
Read AVI tombstone data for header comments from \fIcommentfile\fP. See
/docs/avi_comments.txt for a sample.
.TP
\fB-a\fP \fInum\fP
Specify the number of the audio channel.
.SH EXAMPLES
The command
.PP
.B avimerge -o big.avi -i my_file1.avi my_file2.avi my_file3.avi
.PP
merges the three input files \fImy_file[123].avi\fP into one big AVI-file
\fIbig.avi\fP.
.PP
.B avimerge -o out.avi -i in.avi -p audio2.avi -a 1
.PP
merges an additional audio track as track number 1 to the AVI-file. You can
create audio-only AVI-files using
.PP
.B  transcode -i song.mp3 -x null,mp3 -g 0x0 -y raw -a 1 -o audio2.avi -u 50
.PP
The command
.PP
.B avimerge -o out.avi -i in.avi -p sound.mp3
.PP
merges the file sound.mp3 as an additional audio track into out.avi.
.SH AUTHORS
.B avimerge
was written by Thomas Östreich
.br
<ostreich@theorie.physik.uni-goettingen.de> with contributions from
many others.  See AUTHORS for details.
.SH SEE ALSO
.BR aviindex (1),
.BR avifix (1),
.BR avisplit (1),
.BR tccat (1),
.BR tcdecode (1),
.BR tcdemux (1),
.BR tcextract (1),
.BR tcprobe (1),
.BR tcscan (1),
.BR transcode (1)
