.TH transcode import modules  1 "3th February 2008" "transcode_import(1)"
.SH NAME
transcode \- import modules collection
.SH SYNOPSIS
.B transcode -x module[,module]
.SH COPYRIGHT
\fBtranscode\fP is Copyright (C) 2001-2003 by Thomas Oestreich, 2003-2004 Tilmann
Bitterberg, 2004-2008 Transcode Team
.SH MODULES

.TP
.B \-x \fIvmod\fP[\fI,amod\fP]
video[,audio] import modules [auto,auto]. If omitted, transcode will probe
for appropriate import modules. A full-blown transcode installation has the following import modules:
.RS
.\" Here starts the generated import part, produced by make-module-man.sed
.TP 4
\fBac3\fP \- (audio) AC3
.br
This module has no compile-time dependencies.
This module has no run-time dependencies.
Support for this module is good.
.RS 8
decodes AC3 audio from MPEG program streams or raw streams.
.br
Supported processing formats: audio - PCM AC3, video - none
.RE
.TP 4
\fBavi\fP \- (video) * | (audio) *
.br
This module has no compile-time dependencies.
This module has no run-time dependencies.
Support for this module is good.
.RS 8
RGB/PCM from RIFF AVI files.
.br
Supported processing formats: audio - RAW (pass-through) PCM, video - RAW (pass-through) RGB YUV YUV420
.RE
.TP 4
\fBbktr\fP \- (video) bktr
.br
This module has no compile-time dependencies.
This module has no run-time dependencies.
Support for this module is good.
.RS 8
grabs video frames from bktr(4) devices on BSD systems
.br
Supported processing formats: audio - none, video - RGB YUV YUV420
.RE
.TP 4
\fBdv\fP \- (video) DV | (audio) PCM
.br
This module has no compile-time dependencies.
This module has no run-time dependencies.
Support for this module is good.
.RS 8
Digital Video and PCM audio from RIFF AVI-files or raw streams.
.br
Supported processing formats: audio - PCM, video - RAW (pass-through) RGB YUV DV YUV420
.RE
.TP 4
\fBdvd\fP \- (video) DVD | (audio) MPEG/AC3/PCM
.br
At compile-time libdvdread must be available.
This module has no run-time dependencies.
Support for this module is good.
.RS 8
on-the-fly DVD transcoding.
.br
Supported processing formats: audio - PCM AC3, video - RGB YUV
.RE
.TP 4
\fBffmpeg\fP \- (video) FFmpeg: MSMPEG/MPEG/MJPEG
.br
This module has no compile-time dependencies.
This module has no run-time dependencies.
Support for this module is good.
.RS 8
interface to ffmpeg library supported video codecs and file formats
.br
Supported processing formats: audio - none, video - RAW (pass-through) RGB YUV
.RE
.TP 4
\fBim\fP \- (video) RGB
.br
At compile-time ImageMagick must be available.
At run-time ImageMagick must be present.
Support for this module is fair.
.RS 8
interface to ImageMagick library supported picture codecs and file formats for making animations. Reads images with a counter pattern.
.br
Supported processing formats: audio - none, video - RAW (pass-through) RGB
.RE
.TP 4
\fBimlist\fP \- (video) RGB
.br
At compile-time ImageMagick must be available.
At run-time ImageMagick must be present.
Support for this module is fair.
.RS 8
interface to ImageMagick library supported picture codecs and file formats for making animations. Reads images from a list.
.br
Supported processing formats: audio - RAW (pass-through), video - RAW (pass-through) RGB
.RE
.TP 4
\fBlve\fP \- (video/audio) MPEG/VOB/LVE
.br
At compile-time liblve must be available.
This module has no run-time dependencies.
Support for this module is fair.
.RS 8
imports video from an LVE edit list
.br
Supported processing formats: audio - PCM, video - YUV
.RE
.TP 4
\fBlzo\fP \- (video) LZO
.br
At compile-time lzo must be available.
This module has no run-time dependencies.
Support for this module is good.
.RS 8
imports AVI-files with LZO loss-less compression for video.
.br
Supported processing formats: audio - RAW (pass-through) PCM, video - RAW (pass-through) RGB YUV
.RE
.TP 4
\fBmov\fP \- (video) * | (audio) *
.br
At compile-time libquicktime must be available.
This module has no run-time dependencies.
Support for this module is good.
.RS 8
Quicktime file format, audio/video codecs supported by quicktime4linux.
.br
Supported processing formats: audio - PCM, video - RAW (pass-through) RGB YUV
.RE
.TP 4
\fBmp3\fP \- (audio) MPEG
.br
This module has no compile-time dependencies.
This module has no run-time dependencies.
Support for this module is good.
.RS 8
MPEG audio from program streams or raw streams.
.br
Supported processing formats: audio - PCM, video - none
.RE
.TP 4
\fBmpeg2\fP \- (video) MPEG2
.br
This module has no compile-time dependencies.
This module has no run-time dependencies.
Support for this module is good.
.RS 8
video track from MPEG program streams or raw streams, extracted and decoded by mpeg2dec.
.br
Supported processing formats: audio - none, video - RAW (pass-through) RGB YUV
.RE
.TP 4
\fBmplayer\fP \- (video) rendered by mplayer | (audio) rendered by mplayer
.br
This module has no compile-time dependencies.
At run-time mplayer must be present.
Support for this module is fair.
.RS 8
interface to Mplayer for decoding unsupported codecs, exotic file formats or more ore less broken sources.
.br
Supported processing formats: audio - PCM, video - RAW (pass-through) RGB YUV
.RE
.TP 4
\fBnull\fP \- (video) null | (audio) null
.br
This module has no compile-time dependencies.
This module has no run-time dependencies.
Support for this module is fair.
.RS 8
dummy module, reads from /dev/zero.
.br
Supported processing formats: audio - none, video - none
.RE
.TP 4
\fBnuv\fP \- (video) YUV | (audio) PCM
.br
At compile-time liblzo must be available.
This module has no run-time dependencies.
Support for this module is fair.
.RS 8
interface to NuppelVideo file format.
.br
Supported processing formats: audio - PCM, video - YUV
.RE
.TP 4
\fBogg\fP \- (video) all | (audio) Ogg Vorbis
.br
This module has no compile-time dependencies.
This module has no run-time dependencies.
Support for this module is good.
.RS 8
decodes Ogg Vorbis audio streams.
.br
Supported processing formats: audio - RAW (pass-through) PCM, video - RAW (pass-through) RGB YUV
.RE
.TP 4
\fBraw\fP \- (video) RGB/YUV | (audio) PCM
.br
This module has no compile-time dependencies.
This module has no run-time dependencies.
Support for this module is fair.
.RS 8
RGB/PCM from RIFF AVI/WAVE files or raw streams.
.br
Supported processing formats: audio - PCM, video - RGB YUV YUV420
.RE
.TP 4
\fBsunau\fP \- (audio) pcm
.br
This module has no compile-time dependencies.
This module has no run-time dependencies.
Support for this module is good.
.RS 8
grabs raw PCM audio from audio(4) devices on some BSD systems
.br
Supported processing formats: audio - PCM, video - none
.RE
.TP 4
\fBv4l\fP \- (video) v4l | (audio) PCM
.br
This module has no compile-time dependencies.
This module has no run-time dependencies.
Support for this module is fair.
.RS 8
interface for grabbing sound/video from v4l devices on linux systems.
.br
Supported processing formats: audio - PCM, video - RGB YUV
.RE
.TP 4
\fBv4l2\fP \- (video) v4l2 | (audio) pcm
.br
This module has no compile-time dependencies.
This module has no run-time dependencies.
Support for this module is good.
.RS 8
interface for grabbing sound/video from v4l2 devices on linux systems. prefered over import_v4l.
.br
Supported processing formats: audio - PCM, video - RGB YUV YUV420
.RE
.TP 4
\fBvnc\fP \- (video) VNC
.br
This module has no compile-time dependencies.
At run-time vncrec must be present.
Support for this module is fair.
.RS 8
imports video from the vncrec program.
.br
Supported processing formats: audio - none, video - RAW (pass-through) RGB YUV
.RE
.TP 4
\fBvob\fP \- (video) MPEG-2 | (audio) MPEG/AC3/PCM | (subtitle)
.br
This module has no compile-time dependencies.
This module has no run-time dependencies.
Support for this module is good.
.RS 8
MPEG/AC3 program streams in VOB files (found on unencrypted/ripped DVDs).
.br
Supported processing formats: audio - PCM AC3, video - RAW (pass-through) RGB YUV
.RE
.TP 4
\fBxml\fP \- (video) * | (audio) *
.br
At compile-time libxml2 must be available.
At run-time libxml2 must be present.
Support for this module is fair.
.RS 8
interface to XML files with file listing and frame range produced by kino.
.br
Supported processing formats: audio - RAW (pass-through) PCM, video - RAW (pass-through) RGB YUV DV
.RE
.TP 4
\fByuv4mpeg\fP \- (video) YUV4MPEGx | (audio) WAVE
.br
This module has no compile-time dependencies.
This module has no run-time dependencies.
Support for this module is good.
.RS 8
YUV from video streams produced by mjpegtools (YUV4MPEG) and RIFF WAVE pcm audio.
.br
Supported processing formats: audio - PCM, video - RGB YUV
.RE
.\" Here ends the generated import part, produced by make-module-man.sed
.RE
.IP
To see what your transcode has, do a
.nf
.B ls -1 `tcmodinfo -p`/import*.so
.fi
.IP
It is possible to pass option strings to import modules like to filter modules.
The average user does not this feature and not many modules support it. The syntax is
.B  \-x vmod=options,amod=options
.br
Example
.nf
  \-x rawlist=uyvy,null
.fi
.br
To tell the rawlist import module (which reads images from a list of files) the
colour space of the images.

.PP
.SH SEE ALSO
.BR transcode (1),
.BR tcmodinfo (1),

